[tox]
minversion = 3.10.0
# You can exclude python versions via TOX_SKIP_ENV:
# Example: TOX_SKIP_ENV='py3(12|13)-.*' tox
# More info: https://doc.wikimedia.org/spicerack/master/development.html#running-tests
envlist = py{311,312,313}-{lint_unit, prospector}
skip_missing_interpreters = True

[tox:jenkins]

# If CI is missing a python version we require, it should fail!
# More info on the rationale: https://phabricator.wikimedia.org/T372485
skip_missing_interpreters = false
# Only run lint check and unit tests on different python versions
# CI docker-registry.wikimedia.org/releng/tox-v3 defaults to 3.7, we want 3.11+
envlist = py311-{lint_unit,prospector,sphinx},py313-{lint_unit}

[testenv]
usedevelop = True
download = True
allowlist_externals =
    sed
    {toxinidir}/utils/format-code.sh
description =
    lint_unit: Run ruff, mypy and unit tests
    prospector: Static analysis multi-tool
    sphinx: Build documentation and manpages
    py3: (Python 3)
    py311: (Python 3.11)
    py312: (Python 3.12)
    py313: (Python 3.13)
commands =
    lint_unit: ruff check {posargs}
    lint_unit: mypy --show-error-codes spicerack/
    lint_unit: py.test --strict-markers --cov-report=term-missing --cov=spicerack spicerack/tests/unit {posargs}
    sphinx: python spicerack/tests/sphinx_checker.py '{toxinidir}'
    sphinx: sphinx-build -W -b html '{toxinidir}/doc/source/' '{toxinidir}/doc/build/html'
    sphinx: sphinx-build -W -b man '{toxinidir}/doc/source/' '{toxinidir}/doc/build/man'
    # Fix missing space after bold blocks in man page: https://github.com/ribozz/sphinx-argparse/issues/80
    sphinx: sed -i='' -e 's/^\.B/.B /' '{toxinidir}/doc/build/man/cookbook.1'
    prospector: prospector --no-external-config --profile '{toxinidir}/prospector.yaml' --tool pyroma --tool vulture {posargs} {toxinidir}
deps =
    # Use install_requires and the additional extras_require[tests/prospector] from setup.py
    format: .[format]
    prospector: .[prospector]
    sphinx: .[sphinx]
    !prospector-!format-!sphinx: .[tests]

[testenv:py3-{format}]
