# Base path of the cookbooks. It's usually a checkout of a different repository that has all the cookbooks.
cookbooks_base_dir: /path/to/cookbooks/checkout
# Base directory for cookbook's logs.
logs_base_dir:  /var/log/spicerack
# [optional] Hostname and port to use for the special IRC logging using tcpircbot.
tcpircbot_host: tcpircbot.example.com
tcpircbot_port: 1234

# [optional] Key-value hash of additional parameters to pass to the Spicerack constructor. All keys are optional.
instance_params:
  cumin_config: /etc/cumin/config.yaml  # Cumin's YAML configuration file.
  conftool_config: /etc/conftool/config.yaml  # Conftool's YAML configuration file.
  conftool_schema: /etc/conftool/schema.yaml  # Conftool's YAML schema file.
  debmonitor_config: /etc/debmonitor.conf  # Debmonitor's INI configuration file.
  spicerack_config_dir: /etc/spicerack  # Path to the modules and cookbooks specific configuration files.
  http_proxy: http://proxy.example.com:8080  # HTTP/HTTPS proxy scheme://url:port to use for external calls.
